### ISSUE TITLE
Please add new mode

### ISSUE THREAD

**Issue by TerAnYu** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#2]
Please add new mode, example: osupdate over backup if there is an update
The system will backup only when there is an update and will be updated, as was the first version of the script

----
Прошу добавить новый режим, который будет работать так:
система сделает бэкап только когда есть обновление и обновится, как было в первых версиях скрипта

**Comment by beeyev** [comment]
Нет проблем, сделаю.

**Comment by beeyev** [comment]
Готово, см. описание в теле скрипта.

**Comment by TerAnYu** [comment]
Спасибо!
Всё работает замечательно!
