### ISSUE TITLE
changes for ros 7.1 required

### ISSUE THREAD

**Issue by edvc2331** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#20]
hi,

the current version does not work in ros 7.1

there seems to be an issue with sending an email. syntax changed?

thx!!

**Comment by olivierfaber** [comment]
Yes same here :-)
"
Backup was created.>: invalid BODY
"

**Comment by beeyev** [comment]
Sorry guys, i was quite busy these days, will fix it soon.
If any of you could contribute, I would really appreciate it!

**Comment by edvc2331** [comment]
thanks for your cool script. i use it on all my devices.

the error seems to be gone in router os 7.1.1. tested it with a mickrotik hex-s. 
firmware does not seem to be an issue. worked with 6.47.9 and 7.1.1

in 7.1 there was some error with creating the attachment array and sending the mail

**Comment by robertogaxiola** [comment]
There is still an issue with the option hide-sensitive, now in 7.1 the export always hide sensitive information by default, you  have to use show-sensitive parameter to export those options too, i have manually changed my script in the export section.
