### ISSUE TITLE
Adding Public IP to email details

### ISSUE THREAD

**Issue by Bigben83** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#26]
Hi how easy would it be to add the current Public IP address to the email that is sent out.

`http://ifconfig.co/ip` 
gives the Public IP Address

Something like the below ??
`:local fetchdata [/tool fetch url="http://ifconfig.co/ip" output=user]`
`:local extip ($fetchdata->"data")`
`:local extip [ :pick [ :tostr "$extip" ] 0 [ :find "$extip" "`
`"  ] ]`
`"IP updated to $extip!"`

**Comment by beeyev** [comment]
Hello,
are you talking about this repo? https://github.com/beeyev/Mikrotik-Duckdns-Dynamic-IP-Updater

**Comment by Bigben83** [comment]
Not really, just wanted it in the body of the email for reference if ever needed.

**Comment by beeyev** [comment]
Done!
