### ISSUE TITLE
Not updating firmware on second action!

### ISSUE THREAD

**Issue by jegue** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#43]
installed version 7.11.2;
maybe something change on the new version
7.12.
thanks for this script!

**Comment by shoestar** [comment]
Same here, all devices did the software update but not the firmware.

**Comment by beeyev** [comment]
Thanks guys, I will try to find some time to fix that.

**Comment by beeyev** [comment]
Fixed, thanks guys for bringing attention to the problem!
