### ISSUE TITLE
Mikrotik 7.12 Breaking Changes

### ISSUE THREAD

**Issue by amp88759** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#44]
I think this script is great. 

When the script updates 7.11.2 to 7.12 the script becomes broken because one of the commands has been renamed.

Looking at this https://forum.mikrotik.com/viewtopic.php?t=201345

It states:
**email - rename "address" property to "server"**

Therefore to fix the script find the section of script below

```
#Check proper email config
:if ([:len $emailAddress] = 0 or [:len [/tool e-mail get address]] = 0 or [:len [/tool e-mail get from]] = 0) do={
    :log error ("$SMP Email configuration is not correct, please check Tools -> Email. Script stopped.");
    :error "$SMP bye!";
```

change the word address (after get) to **server**

Apply the script.

When updating from 7.11.2 to 7.12 the script failed. The routerOS was updated but the routerboard firmware was not.

I hope this helps someone!

**Comment by beeyev** [comment]
Thanks for finding the solution, I really appreciate it.
I will make a fix asap.

**Comment by amp88759** [comment]
No problem at all.

**Comment by beeyev** [comment]
Fixed, thanks for your help, mate!

**Comment by amp88759** [comment]
Hi Alex

Thanks for recognising that: not a problem. My dad who’s 80 told me he
didn’t get an email about ‘his router’ this morning. Plagues me to death
with ‘operator error’.

This time he was right! 🤣🤣

Best wishes

Andrew
