### ISSUE TITLE
ROS 7.13 - invalid BODY error

### ISSUE THREAD

**Issue by cyrq** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#47]
`Error sending e-mail <Bkp&Upd: Device - MikroTik. No new OS updates. Backup was created.>: invalid BODY`

**Comment by lordforall** [comment]
Script broken for me too in v7.13

**Comment by cyrq** [comment]
Sorry for the confusion - this was actually an issue with my SMTP Relay.
