### ISSUE TITLE
Failure since update to RouterOS 7.14.2

### ISSUE THREAD

**Issue by amp88759** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#52]
Receive the error message in the email:

**Mikrotik couldn't get any information about new RouterOS from server!**

**Comment by amp88759** [comment]
I have manually run the script and it appears to be fully functional now. I will wait for the automatic backup and update tomorrow morning to see if the script fails again.

**Comment by Penticore** [comment]
Here is the test from this evening:

```
02:00:00 script,info Bkp&Upd: script "Mikrotik RouterOS automatic backup & update" started.
02:00:00 script,info Bkp&Upd: Script Mode: osupdate, forceBackup: false
02:00:01 fetch,info Download from ipv4.mikrotik.ovh FINISHED
02:00:01 script,info Bkp&Upd: Performing the first step.
02:00:01 script,info Bkp&Upd: Checking for new RouterOS version. Current version is: 7.14.2
02:00:10 script,warning Bkp&Upd: There is a problem getting information about new RouterOS from server.
02:00:10 script,info Bkp&Upd: Checking If the script needs to create a backup.
02:00:10 script,info Bkp&Upd: There is no need to create a backup.
02:00:10 script,info Bkp&Upd: Sending email message, it will take around half a minute...
02:00:12 e-mail,info sent <Bkp&Upd: Device - azurea. Error: No data about new RouterOS!> to: asd@asd
02:00:41 script,info Bkp&Upd: script "Mikrotik RouterOS automatic backup & update" completed it's job.r
02:00:41 script,info 
02:01:05 script,info 
02:01:05 script,info Bkp&Upd: script "Mikrotik RouterOS automatic backup & update" started.
02:01:05 script,info Bkp&Upd: Script Mode: osupdate, forceBackup: false
02:01:06 fetch,info Download from ipv4.mikrotik.ovh FINISHED
02:01:06 script,info Bkp&Upd: Performing the first step.
02:01:06 script,info Bkp&Upd: Checking for new RouterOS version. Current version is: 7.14.2
02:01:13 script,info Bkp&Upd: System is already up to date.
02:01:13 script,info Bkp&Upd: Checking If the script needs to create a backup.
02:01:13 script,info Bkp&Upd: There is no need to create a backup.
02:01:13 script,info Bkp&Upd: script "Mikrotik RouterOS automatic backup & update" completed it's job.r
```

**Comment by Penticore** [comment]
note: The script works fine on the old switchers (CRS125 - mipsbe), but not on the newer routers (RB4011 - arm and ccr1009 - tile).

**Comment by proteus88** [comment]
Same problem, sometimes works sometimes its not working but it always works if I run the script manually.

When the schedule runs I get "Bkp&Upd: There is a problem getting information about new RouterOS from server."

**Comment by Penticore** [comment]
It's fixed. I have recreated the scrips on the routers from scratch and it's working well.

**Comment by proteus88** [comment]
I did put the updated script a few days ago because of this problem, its the same for me. I only added email and password.

**Comment by beeyev** [comment]
Also, ensure that the script is not scheduled for on-the-hour times, such as 13:00 or 17:00, because MikroTik servers are highly loaded during those periods. It's preferable to schedule the script at random minutes, like 13:46, for example.
