### ISSUE TITLE
Script error for RouterOS 7.15

### ISSUE THREAD

**Issue by lc1ferr** [beeyev/Mikrotik-RouterOS-automatic-backup-and-update#53]
There was an error while running the script. The log shows: 'executing script BackupAndUpdate from winbox failed, please check it manually"

**Comment by beeyev** [comment]
Yes, you need to execute the script manually and you will see the actual error.

**Comment by beeyev** [comment]
Please provide a screenshot of what the console is showing after you execute this command:
```
/system script run BackupAndUpdate;
```

**Comment by lc1ferr** [comment]
bad command name routerboard (line 236 column 42)

**Comment by beeyev** [comment]
Provide the details about your device

**Comment by lc1ferr** [comment]
Device information:
Identity: MikroTik
Model: CloudHostedRouter
Serial number: --
Current RouterOS: 7.15 (stable)


The command '/system resource get board-name' executed in the console did not return any content. Therefore, on line 217, the 'do={
isSoftBased true;}' command was not executed.

**Comment by beeyev** [comment]
Could you please execute this command in your console, and tell me what it returns:
```
:put [/system resource get board-name]
```

**Comment by Lc1fer** [comment]
CHR QEMU Standard PC (i440FX + PIIX, 1996)

**Comment by lc1ferr** [comment]
CHR QEMU Standard PC (i440FX + PIIX, 1996)

**Comment by beeyev** [comment]
I created a bugfix, but could you please check if it works first.

Here is the new version of the script:
https://github.com/beeyev/Mikrotik-RouterOS-automatic-backup-and-update/blob/beeyev-patch-1/BackupAndUpdate.rsc

This is [the PR](https://github.com/beeyev/Mikrotik-RouterOS-automatic-backup-and-update/pull/54/files) with changes

**Comment by lc1ferr** [comment]
The script is now working correctly. Thank you very much!
